### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by brettz9** [inexorabletash/polyfill#120]
Hi,

Are you open to a kind of progressive enhancement which exports those interfaces in your polyfill to Node as they become adapted to provide support?

I was working on one for `URL` though now I (albeit gratefully) see it significantly reworked but was hoping to avoid the need for reapplying downstream again in the future.

In combination with the likes of `jsdom` (if not portions being directly required into it), this can be very handy on the Node side, though beyond that, it also can foster polyglot development beyond typical DOM simulation (e.g., with our `IndexedDBShim` project getting to work in either environment or with `URL` being attractive as an API that can work in the browser or Node (since the browser didn't (couldn't?) just adapt the Node `url` module))...

Although one would think we learned the lesson with the need for web standards, some seem to be indifferent to the very attractive possibility of greater polyglot development between Node and the browser. IMO, just because the environments have some differences doesn't mean the wheel needs to be reinvented...

**Comment by inexorabletash** [comment]
Re: URL - for non-DOM use you may want to consider https://github.com/github/url-polyfill/blob/master/url.js - the URL implementation here is mostly a wrapper around the HTMLAnchorElement since that already has most of the complexity implicitly implemented in the browser.

I really don't want to add much complexity here. I use this for my projects and share it for others but it's not trying to replicate the entire web platform in JS. Other projects can do that if they wish.

**Comment by brettz9** [comment]
Thanks for the info, and understood.
