### ISSUE TITLE
Uint8Array crashes IE9

### ISSUE THREAD

**Issue by ghost** [inexorabletash/polyfill#7]
Hello,

can you check out the Uint8Array because when I use it to convert a pdf file with this steps:

var ab = new ArrayBuffer(byteString.length);
var ia = new Uint8Array(ab);
for (var i = 0; i < byteString.length; i++) {
         ia[i] = byteString.charCodeAt(i);
}

IE9 crashes when executing this line:
var ia = new Uint8Array(ab);

PS: ArrayBuffer works great.

Thanks

**Comment by zky829** [comment]
I'm experiencing the same issue as the OP. Was there any further communication on this?

**Comment by inexorabletash** [comment]
The last question doesn't have a good answer. The instructions for using methods instead of indexed property getters/setters are described above. But passing the resulting polyfill object to the Blob constructor isn't going to work, IE9 doesn't even support a Blob constructor.

Otherwise... what's not clear from the above?
