### ISSUE TITLE
Array MAX_ARRAY_LENGTH value

### ISSUE THREAD

**Issue by sendyhalim** [inexorabletash/polyfill#90]
Hi I'm getting `RangeError: Array too large for polyfill`, it happens because of `polyfill` limits the array size. I'm looping through large image pixels. I would be happy to submit a pull request if it's possible to remove the MAX_ARRAY_LENGTH limitation.

https://github.com/inexorabletash/polyfill/blob/ba16411f4245a394b2074af12be5296756d3c783/typedarray.js#L43

```
// Beyond this value, index getters/setters (i.e. array[0], array[1]) are so slow to
// create, and consume so much memory, that the browser appears frozen.
var MAX_ARRAY_LENGTH = 1e5
```

**Comment by inexorabletash** [comment]
The limit is put in there due to memory constraints on the older browsers (IE8, IE9) when creating the indexed accessors. So I added an TYPED_ARRAY_POLYFILL_NO_ARRAY_ACCESSORS option (`self.TYPED_ARRAY_POLYFILL_NO_ARRAY_ACCESSORS=true` to enable it), which prohibits the creation of the accessors. 

Pick one of:

* Using short arrays: just use the polyfill as-is

* Using long arrays: set `TYPED_ARRAY_POLYFILL_NO_ARRAY_ACCESSORS`, use the non-standard `get()` to inspect array elements, and add that for native typed arrays e.g.:

```js
[
 'Uint8Array', 'Uint16Array', 'Uint32Array', 'Uint8ClampedArray',
 'Int8Array', 'Int16Array', 'Int32Array',
 'Float32Array', 'Float64Array'].forEach(function(t) {
  t.prototype.get = function(i) { return this[i]; }
});
```

Setting must be done with `ta.set([v], i)` instead of `ta[i] = v`

**Comment by sendyhalim** [comment]
@inexorabletash yeah that makes sense! Thanks for the response :D
